title: "The Infinite Pause"
tagline: "Shiva. Shakti. Beyond Time."
description: "A cinematic sanctuary for Vedic resonance. Experience the stillness of Shiva through the Shri Rudrashtakam and ancient Sanskrit poetry."
url: "https://theinfinitepause.github.io"
author: "The Infinite Pause"

theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

social:
  name: The Infinite Pause
  links:
    - https://www.youtube.com/channel/UCu5KQpf_mXvtZQNXT5lFlhw
    - https://in.pinterest.com/theinfinitepause
    - https://www.instagram.com/thelastwitness_tip/reels/
    - https://www.facebook.com/profile.php?id=61580738874152

image: /ShriRudrashtakamv1-2.png

minima:
  skin: dark
  custom_css:
    - assets/css/custom.css
  social_links:
    - { platform: youtube, user_url: "https://www.youtube.com/channel/UCu5KQpf_mXvtZQNXT5lFlhw" }
    - { platform: pinterest, user_url: "https://in.pinterest.com/theinfinitepause" }
    - { platform: instagram, user_id: "thelastwitness_tip" }
    - { platform: facebook, user_id: "61580738874152" }

header_pages:
  - about.md
  - index.md
show_excerpts: true
